###
GET {{origin}}/

> {%
    client.test("Response status", function () {
        let expected = 200;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response content-type header charset", function () {
        let expected = 'UTF-8';
        let actual = response.contentType.charset;
        client.assert(actual === expected, `Expected '${expected}, but got '${actual}'`)
    });
%}

###
GET {{origin}}/status

> {%
    client.test("Response status", function () {
        let expected = 200;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"message":"server is running","status":"ok","version":"0.1.0"};
        let actual = response.body;
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
        client.assert(expected.status === actual.status, `Expected body '${expected.status}', actual '${actual.status}'`);
        client.assert(expected.version === actual.version, `Expected body '${expected.version}', actual '${actual.version}'`);
    });
%}

### /api/records - BME280
< {%
    request.variables.set("record_id", $uuid);
    request.variables.set("timestamp", $isoTimestamp)
%}

PUT {{origin}}/api/records
Content-Type: application/json
access_key: {{access_key}}

{
    "id": "{{record_id}}",
    "timestamp": "{{timestamp}}",
    "reading": {
        "BME280": {
            "temperature": 22,
            "pressure": 101000.01,
            "humidity": 0.45
        }
    }
}

> {%
    client.test("Response status", function () {
        let expected = 201;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"message": "record saved successfully", "id": "29b6ae59-8faa-4c42-b503-57cb10fe0508"};
        let actual = response.body;
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
    });
%}

### /api/records - DS18B20
< {%
    request.variables.set("record_id", $uuid);
    request.variables.set("timestamp", $isoTimestamp)
%}

PUT {{origin}}/api/records
Content-Type: application/json
access_key: {{access_key}}

{
    "id": "{{record_id}}",
    "timestamp": "{{timestamp}}",
    "reading": {
        "DS18B20": {
            "device_name": "0000003e33d5",
            "raw_reading": 22375
        }
    }
}

> {%
    client.test("Response status", function () {
        let expected = 201;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"message": "record saved successfully", "id": "29b6ae59-8faa-4c42-b503-57cb10fe0508"};
        let actual = response.body;
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
    });
%}

###
# Get a specific record by id depends on the record_id existence in the test data
< {%
    request.variables.set("record_id", "7e9b1a33-05fb-48e3-86b6-21ddc873c06f");
%}

GET {{origin}}/api/records/{{record_id}}
Content-Type: application/json
access_key: {{access_key}}

> {%
    client.test("Response status", function () {
        let expected = 200;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {
            "record": {
                "id": "7e9b1a33-05fb-48e3-86b6-21ddc873c06f",
                "reading": {
                    "DS18B20": {
                        "device_name": "0000003e33d5",
                        "raw_reading": 22123
                    }
                },
                "timestamp": "2026-02-27T09:32:45Z"
            }
        };
        let actual = response.body;
        client.assert(expected.record.id === actual.record.id, `id: expected '${expected.record.id}', actual '${actual.record.id}'`)
        client.assert(expected.record.timestamp === actual.record.timestamp, `timestamp: expected '${expected.record.timestamp}', actual '${actual.record.timestamp}'`)
        client.assert(expected.record.reading.DS18B20.device_name === actual.record.reading.DS18B20.device_name, `device_name: expected '${expected.record.reading.DS18B20.device_name}', actual '${actual.record.reading.DS18B20.device_name}'`)
        client.assert(expected.record.reading.DS18B20.raw_reading === actual.record.reading.DS18B20.raw_reading, `raw_reading: expected '${expected.record.reading.DS18B20.raw_reading}', actual '${actual.record.reading.DS18B20.raw_reading}'`)
    });
%}

###
# GET /api/records/{record_id} with a random id should fail (almost) always
< {%
    request.variables.set("record_id", $uuid);
%}

GET {{origin}}/api/records/{{record_id}}
Content-Type: application/json
access_key: {{access_key}}

> {%
    client.test("Response status", function () {
        let expected = 404;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"error": "record not found", "message": "No record with the supplied id was found"};
        let actual = response.body;
        client.assert(expected.error === actual.error, `Expected error '${expected.error}', actual error '${actual.error}'`)
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
    });
%}

###

GET {{origin}}/api/records
access_key: {{access_key}}

> {%
    client.test("Response status", function () {
        let expected = 200;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });
%}

###
# GET /api/records without authorization must fail

GET {{origin}}/api/records

> {%
    client.test("Response status", function () {
        let expected = 401;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });
%}

###
# As the client sets the `id`, records are added with method PUT, not POST

POST {{origin}}/api/records

> {%
    client.test("Response status", function () {
        let expected = 405;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });
%}

###
# The path /api/record (singular!) is invalid

GET {{origin}}/api/record

> {%
    client.test("Response status", function () {
        let expected = 404;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });
%}

###
# The path /api/record (singular!) is invalid

POST {{origin}}/api/record

> {%
    client.test("Response status", function () {
        let expected = 404;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });
%}

###
# The path /api/record (singular!) is invalid

PUT {{origin}}/api/record

> {%
    client.test("Response status", function () {
        let expected = 404;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Length", function () {
        let expected = "0";
        let actual = response.headers.valueOf( "Content-Length");
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "text/plain";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = null;
        let actual = response.body;
        client.assert(expected === actual, `Expected null, actual '${actual}'`);
    });
%}
