### GET root
GET {{origin}}/

> {%
    client.test("Response status", function () {
        let expected = 200;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response content-type header charset", function () {
        let expected = 'UTF-8';
        let actual = response.contentType.charset;
        client.assert(actual === expected, `Expected '${expected}, but got '${actual}'`)
    });
%}

### GET server status
GET {{origin}}/status

> {%
    client.test("Response status", function () {
        let expected = 200;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"message":"server is running","status":"ok","version":"0.1.0"};
        let actual = response.body;
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
        client.assert(expected.status === actual.status, `Expected body '${expected.status}', actual '${actual.status}'`);
        client.assert(expected.version === actual.version, `Expected body '${expected.version}', actual '${actual.version}'`);
    });
%}

### PUT BME280 record
< {%
    request.variables.set("record_id", $uuid);
    request.variables.set("timestamp", $isoTimestamp)
%}

PUT {{origin}}/api/record
Content-Type: application/json

{
    "id": "{{record_id}}",
    "timestamp": "{{timestamp}}",
    "reading": {
        "BME280": {
            "temperature": 22,
            "pressure": 101000.01,
            "humidity": 0.45
        }
    }
}

> {%
    client.test("Response status", function () {
        let expected = 201;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"message": "record saved successfully", "id": "29b6ae59-8faa-4c42-b503-57cb10fe0508"};
        let actual = response.body;
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
    });
%}

### PUT DS18B20 record
< {%
    request.variables.set("record_id", $uuid);
    request.variables.set("timestamp", $isoTimestamp)
%}

PUT {{origin}}/api/record
Content-Type: application/json

{
    "id": "{{record_id}}",
    "timestamp": "{{timestamp}}",
    "reading": {
        "DS18B20": {
            "device_name": "0000003e33d5",
            "raw_reading": 22375
        }
    }
}

> {%
    client.test("Response status", function () {
        let expected = 201;
        let actual = response.status;
        client.assert(expected === actual, `Expected status '${expected}', actual '${actual}'`);
    });

    client.test("Response Content-Type", function () {
        let expected = "application/json";
        let actual = response.contentType.mimeType;
        client.assert(expected === actual, `Expected content type '${expected}', actual '${actual}'`);
    });

    client.test("Response body", function () {
        let expected = {"message": "record saved successfully", "id": "29b6ae59-8faa-4c42-b503-57cb10fe0508"};
        let actual = response.body;
        client.assert(expected.message === actual.message, `Expected body '${expected.message}', actual '${actual.message}'`);
    });
%}
